#!/bin/bash
#
# Copyright © 2011-2012 Akiban Technologies, Inc.  All rights reserved.
# 
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License v1.0 which
# accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# This program may also be available under different license terms.
# For more information, see www.akiban.com or contact licensing@akiban.com.
# 
# Contributors:
# Akiban Technologies, Inc.
# 
#

#-----------------------------
# This is a working template for a simple script to perform crash
# recovery testing in Persistit.  This script should be run from the
# root directory of the Persistit project. As configured, this
# script runs the recovery_1.plan stress test for 60 seconds, 
# kills the JVM and then runs the recovery_2.plan to verify
# consistency.
#-----------------------------

sleep_time=180
datapath="/tmp/persistit_test_data"

jvm_options="-Xmx2G -Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y"

testrunner_command="java $jvm_options -cp `find . -name akiban-persistit\*with-dependencies\*.jar` -Dstress_recovery_test_signature=1 "

command="$testrunner_command com.persistit.stress.Recovery1 datapath=$datapath"
echo "$command  > $datapath/recovery.log"
$command > $datapath/recovery.log &

echo "Sleeping for $sleep_time seconds"
sleep $sleep_time

while background_pid=`pgrep -f "stress_recovery_test_signature=1"`
do
  echo "kill -9 $background_pid"
  kill -9 $background_pid
  sleep 1
done

echo -----

command="$testrunner_command com.persistit.stress.Recovery2 datapath=$datapath"
echo $command
$command
sleep 2

