#!/bin/bash
echo
echo "------------ starting cycle $1 ----------------"
mkdir /tmp/persistit_test_data
./src/test/resources/stress-recovery
mv /tmp/persistit_test_data /home/akiba/crash-recovery-tests/run_$1
echo "------------   ending cycle $1 ----------------"
echo

