#!/bin/bash
#
# Copyright © 2011-2012 Akiban Technologies, Inc.  All rights reserved.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3 (only) of the
# License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# This program may also be available under different license terms. For more
# information, see www.akiban.com or contact licensing@akiban.com.
#

#-----------------------------
# This is a working template for a simple script to perform crash
# recovery testing in Persistit.  This script should be run from the
# root directory of the Persistit project. As configured, this
# script runs the recovery_1.plan stress test for 60 seconds, 
# kills the JVM and then runs the recovery_2.plan to verify
# consistency.
#-----------------------------

sleep_time=180
datapath="/tmp/persistit_test_data"

jvm_options="-Xmx2G -Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y"

testrunner_command="java $jvm_options -cp `find . -name akiban-persistit\*with-dependencies\*.jar` -Dstress_recovery_test_signature=1 "

command="$testrunner_command com.persistit.stress.Recovery1 datapath=$datapath"
echo "$command  > $datapath/recovery.log"
$command > $datapath/recovery.log &

echo "Sleeping for $sleep_time seconds"
sleep $sleep_time

while background_pid=`pgrep -f "stress_recovery_test_signature=1"`
do
  echo "kill -9 $background_pid"
  kill -9 $background_pid
  sleep 1
done

echo -----

command="$testrunner_command com.persistit.stress.Recovery2 datapath=$datapath"
echo $command
$command
sleep 2

